name: cicd
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo apt-get update && sudo apt-get -y -qq install clang-tidy cppcheck cflow spell
    - name: make
      run: make LLVM_VERSION=10
      working-directory: .
